name: my CASE app

entities:
  Post:
    nameSingular: post
    namePlural: post
    properties:
      title:
        type: text
      status:
        type: choice
        choices:
          - draft
          - published
        sequential: true
      price:
        type: money
        currency: USD
    hasMany:
      comments: { type: Comment, eager: true }

  Comment:
    seedCount: 100
    belongsTo:
      post: { type: Post }
    properties:
      body: { type: text }
      price: { type: money, currency: JPY }
