name: my CASE app

entities:
  Post:
    nameSingular: post
    namePlural: post
    properties:
      title:
        type: text
      status:
        type: choice
        choices:
          - draft
          - published
        sequential: true
      price:
        type: money
        currency: USD

  Comment:
    seedCount: 100
