name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:    
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          issue-message: 'Welcome to Manifest, thank you for adding your first issue !'
          pr-message: 'Welcome to Manifest, thank you for adding your first PR !'
